-- 코드를 입력하세요
SELECT INFO.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF FH
INNER JOIN ICECREAM_INFO INFO
WHERE FH.FLAVOR = INFO.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY FH.TOTAL_ORDER