-- https://school.programmers.co.kr/learn/courses/30/lessons/151139

SELECT MONTH(h.START_DATE) as 'MONTH', h.CAR_ID, COUNT(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
WHERE h.CAR_ID in (
    SELECT c.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as c
    WHERE MONTH(c.START_DATE) between 8 and 10 and YEAR(c.START_DATE) = 2022
    GROUP BY c.CAR_ID
    HAVING COUNT(*) >= 5
) and MONTH(h.START_DATE) between 8 and 10 and YEAR(h.START_DATE) = 2022
GROUP BY h.CAR_ID, MONTH(h.START_DATE)
HAVING RECORDS >= 1
ORDER BY MONTH(h.START_DATE), h.CAR_ID DESC;